{% set version = "0.7.0" %}

package:
  name: nose-timer
  version: {{ version }}

source:
  fn: nose-timer-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/nose-timer/nose-timer-{{ version }}.tar.gz
  sha256: b76baab514aff39ac567455aaecd63b881127f922e9632b1f814f96575f562e8
  patches:
    ############################################################
    # Drop unneeded ordereddict dependency.                    #
    #                                                          #
    # xref: https://github.com/mahmoudimus/nose-timer/pull/84  #
    ############################################################
    - PR_84.diff

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - nose
    - termcolor

test:
  imports:
    - nosetimer

  commands:
    - nosetests --with-timer

about:
  home: https://github.com/mahmoudimus/nose-timer
  license: MIT
  license_file: LICENSE
  summary: A timer plugin for nosetests.

extra:
  recipe-maintainers:
    - jakirkham
