{% set version = "0.7.3" %}

package:
  name: nose-timer
  version: {{ version }}

source:
  fn: nose-timer-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/nose-timer/nose-timer-{{ version }}.tar.gz
  sha256: 84743e05fc940868f5b6e379ed2a3f7da3fa49cdd72c3f531c893868b12adf41
  patches:
    ############################################################
    # Drop unneeded ordereddict dependency.                    #
    #                                                          #
    # xref: https://github.com/mahmoudimus/nose-timer/pull/84  #
    ############################################################
    - PR_84.diff

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - nose
    - termcolor

test:
  imports:
    - nosetimer

  commands:
    - nosetests --with-timer

about:
  home: https://github.com/mahmoudimus/nose-timer
  license: MIT
  license_file: LICENSE
  summary: A timer plugin for nosetests.

extra:
  recipe-maintainers:
    - jakirkham
