travis:
  secure:
    BINSTAR_TOKEN: FqRZJSMPDpoXtdxiqEBqFK9xpvN4Rwmb1WMAhxsI1QGXDkme+6su8CRkdnvXOOaecE4IOSeqrsh3lQvBa0l+6hPMSBofOT3y4y64nFQD0hg1jL3aSA7Ar7U3H4JjspdAc+FYv40yppYnPUkqfXuTF4xxoxB0RCzHucI6ZIJod8dkmQCC5I1C/GXk0u4LYbij9SYjU1a5+/Bs7gSU0Hf3jEaWUjUmMZ3bGXe4YN/MLg9AdC2wVs92eME7Y/7yOkivWdGl0eNkCnkwkt8iPJeVoT2XC6xMPnbvVMxw27kMNiAIHdOSNsj852zbkx+ynZ1Obqe3Y59XFGlbT2UKUeb16Zb4hF1nWeGJVBB9kWSMai7ObBn4yjdiDMBtLgjjOBuhOdswJyCXutMhcY9xslOBQEcFE6G6BiUZPbLtyXOK2LArSb6gEFWVdI0BFDdjErgHVSd8MFbQNmVvLeKG+MqlOz75z1L2NEmWOihG/t01lNPLZ17whlIW+Q45cVsMROPhY1Pq+q/9QdinAZ/tE1mT/Sv5r+6aiaXtSn04H0NEUXJc8V/WQPg7TFol+u/DdzRitgFUZoH1CTHUhPvaj+TWv3Rq7aJ+miKyvCB0pC2WqnpltvfV9/JwrseyLLYg31rxIadQv4ZNWGJ11s9CP/mbj2wnj3Vui4izOwbgMCMIc9g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
