travis:
  secure:
    BINSTAR_TOKEN: BRNN7ShnTPAcKP3JDy8hK918x8l56O3ZA1YL+K/H0IB7tfm8kREp3y9PGZdmHXb3GqMcaR+DTJEHpVdWr53EkR+wPxqpqkmocVf15/udzXT2k5LQVCl0uunzUnNt9oeRlwnlS7k1SPVuhV/B5oFnrfbtRGrd1TlYqqc1eBd2m0QT7bs/4ogJerCZSKxWAKDRJiIupRFYdc/gXjHb9kSMbeAtDDBjexwGH54EvfSLvOF0Xl617qafZxRhc05VKuuANg+A0//NCusX/qNo6rxIatASgZFiCtMDL6Y6gnfWG7RNY7rukLygEofePnkh73G541/BeD7qN0jKTffwEL/U5FPmF0hpgW0DIMViff0n7IkUvCscBcG3qZEz5+IB+W5wJm/ONBxZmc4Jn/uhgY4X84GW4q+Yz73f80o3NMOIto11GqghfbKgxUWfuQChaK69w4PabnqOiafJHaSVmg5ikxK2WH7KqHm2jyw5ygk9YTo5eP+Je0ZWZxirZqktUqiXm0XZpwU2gbLY2kPnR88eciUMa20AAdHJgpLNI2vb9hJ0VKOgtmGnM7oaOnwED9EF/0okqf/wfXv873KBKqvOw/O2eM7TARgs0Ft2drRBsdNEHMidrA9Kg31jjDIkGwAmLUhEjrX/zvJj9ZUg0xgryDMCpvx9MJ61a+kyQCAmACw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
